#Pingi-Backend Docker Compose

services:
  app:
    build: .
    container_name: pingi-backend
    restart: unless-stopped
    ports:
      - "8100:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:pingi123!!@pingi-postgres:5432/pingi?schema=public
      NODE_ENV: development
      PORT: "8000"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - pingi_net

volumes:
  uploads_data:

networks:
  pingi_net:
    external: true
